FROM apache/airflow:2.8.1-python3.11

USER root

# Install OpenJDK 17 for PySpark
RUN apt-get update && \
    apt-get install -y openjdk-17-jre-headless && \
    apt-get clean

# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow

# Install PySpark into the Airflow container
RUN pip install --no-cache-dir pyspark==3.5.0 great_expectations==0.18.12